- alias: 'Enable Circadian Lighting'
  trigger:
    platform: homeassistant
    event: start
  action:
    service: switch.turn_on
    entity_id: switch.circadian_lighting_circadian_lighting

- alias: 'Lights on at morning'
  trigger:
    platform: time
    at: "08:00:00"
  condition:
    condition: state
    entity_id: group.home_devices
    state: 'home'
  action:
    service: homeassistant.turn_on
    entity_id: group.lights_main

- alias: 'Lights on at sunset'
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
    below: 0
  condition:
    condition: state
    entity_id: group.home_devices
    state: 'home'
  action:
    service: homeassistant.turn_on
    entity_id: group.lights_overhead

- alias: 'Lights on for cloudy days'
  trigger:
    platform: numeric_state
    entity_id:  sensor.dark_sky_cloud_coverage
    above: 55
  condition:
    - condition: state
      entity_id: group.home_devices
      state: 'home'
    - condition: time
      after: '09:00:00'
      before: '18:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: group.lights_overhead

- alias: 'Lights on when home'
  trigger:
    platform: state
    entity_id: group.home_devices
    to: 'home'
  condition:
    condition: time
    after: '09:00:00'
    before: '20:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: group.lights_main

- alias: 'Home, disable security, nest home'
  trigger:
    platform: state
    entity_id: group.home_devices
    to: 'home'
  action:
    - service: climate.set_preset_mode
      entity_id: climate.hallway
      data:
        preset_mode: none
    - service: switch.turn_off
      entity_id: switch.foscam_security

- alias: 'Away, enable security, lights off, nest away, tv off'
  trigger:
    platform: state
    entity_id: group.home_devices
    to: 'not_home'
    from: 'home'
    for: "00:10:00"
  action:
    - service: climate.set_preset_mode
      entity_id: climate.hallway
      data:
        preset_mode: away
    - service: homeassistant.turn_off
      entity_id: group.lights
    - service: switch.turn_off
      entity_id: switch.tv
    - service: switch.turn_on
      entity_id: switch.foscam_security

- alias: 'TV on, lights off, switch rotel input'
  trigger:
    platform: state
    entity_id: switch.tv
    to: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: group.lights_tv
    - service: switch.turn_on
      entity_id: switch.rotel_input_1
