- alias: 'Enable Circadian Lighting'
  trigger:
    platform: homeassistant
    event: start
  action:
    service: switch.turn_on
    entity_id: switch.circadian_lighting_circadian_lighting

- alias: '8am lights on when home'
  trigger:
    platform: time
    at: "08:00:00"
  condition:
    condition: state
    entity_id: group.home_devices
    state: 'home'
  action:
    service: homeassistant.turn_on
    entity_id: group.lights_morning

- alias: 'Sunset lights on'
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
    below: 0
  action:
    service: homeassistant.turn_on
    entity_id: group.lights_sunset

- alias: 'Midnight lights off when away'
  trigger:
    platform: time
    at: "23:59:00"
  condition:
    condition: state
    entity_id: group.home_devices
    state: 'not_home'
  action:
    service: homeassistant.turn_off
    entity_id: group.lights


# - alias: 'Lights on for cloudy days'
#   trigger:
#     platform: numeric_state
#     entity_id:  sensor.dark_sky_cloud_coverage
#     above: 55
#   condition:
#     - condition: state
#       entity_id: group.home_devices
#       state: 'home'
#     - condition: time
#       after: '09:00:00'
#       before: '18:00:00'
#   action:
#     service: homeassistant.turn_on
#     entity_id: group.lights_overhead
#
#
- alias: 'Away enable security'
  trigger:
    platform: state
    entity_id: group.home_devices
    to: 'not_home'
    # from: 'home'
    # for: "00:10:00"
  action:
    - service: switch.turn_on
      entity_id: switch.foscam_security

- alias: 'Away lights & tv off'
  trigger:
    platform: state
    entity_id: group.home_devices
    to: 'not_home'
    for: "00:15:00"
  action:
    - service: homeassistant.turn_off
      entity_id: group.lights
    - service: switch.turn_off
      entity_id: switch.tv

- alias: 'Away nest off'
  trigger:
    platform: state
    entity_id: group.home_devices
    to: 'not_home'
  action:
    - service: climate.set_preset_mode
      entity_id: climate.hallway
      data:
        preset_mode: away

- alias: 'Home disable security'
  trigger:
    platform: state
    entity_id: group.home_devices
    to: 'home'
  action:
    service: switch.turn_off
    entity_id: switch.foscam_security

- alias: 'Home lights on'
  trigger:
    platform: state
    entity_id: group.home_devices
    to: 'home'
  action:
    service: homeassistant.turn_on
    entity_id: group.lights_home

- alias: 'Home nest on'
  trigger:
    platform: state
    entity_id: group.home_devices
    to: 'home'
  action:
    service: climate.set_preset_mode
    entity_id: climate.hallway
    data:
      preset_mode: none

- alias: 'TV on, switch receiver'
  trigger:
    platform: state
    entity_id: switch.tv
    to: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.rotel_input_1
