- alias: 'Start Circadian Lighting'
  trigger:
    platform: homeassistant
    event: start
  action:
    service: switch.turn_on
    entity_id: switch.circadian_lighting_circadian_lighting

- alias: 'Turn on Lights at Sunset'
  trigger:
    platform: sun
    event: sunset
    offset: "-01:00:00"
  action:
    service: scene.turn_on
    entity_id: scene.lights_at_sunset
