- platform: generic
  name: Living Room
  still_image_url: !secret foscam_living

- platform: generic
  name: Office
  still_image_url: !secret foscam_office

# weather
- platform: generic
  name: Miami Weather
  still_image_url: "https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?num=10&type=N0R&mapx=400&mapy=240&brand=wui&delay=15&frame=0&scale=1&transx=0&transy=0&severe=1&smooth=0&centerx=400&centery=240&station=AMX&rainsnow=1&lightning=0&noclutter=0&showlabels=1&showstorms=0"

# miami traffic cameras
- platform: generic
  name: Brickell
  still_image_url: https://fl511.com/map/Cctv/735--2

- platform: generic
  name: I95 Biscayne
  still_image_url: https://fl511.com/map/Cctv/656--2

- platform: generic
  name: I95 Wynwood
  still_image_url: https://fl511.com/map/Cctv/759--2

- platform: generic
  name: Julia Tuttle Causeway
  still_image_url: https://fl511.com/map/Cctv/658--2

- platform: generic
  name: McArthur Causeway
  still_image_url: https://fl511.com/map/Cctv/838--2

# android ip webcam
# - platform: mjpeg
#   mjpeg_url: http://lg-g3:8080/video
#   name: Living Room
# - platform: mjpeg
#   mjpeg_url: http://10.0.73.42:8080/video
#   name: Living Room 2
