- platform: foscam
  ip: 10.0.73.85
  username: !secret foscam_username
  password: !secret foscam_password

# miami cameras
- platform: mjpeg
  name: miami
  mjpeg_url: http://204.195.147.57:81/mjpg/video.mjpg

# android ip webcam
# - platform: mjpeg
#   mjpeg_url: http://lg-g3:8080/video
#   name: Living Room
# - platform: mjpeg
#   mjpeg_url: http://10.0.73.42:8080/video
#   name: Living Room 2
