homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 10
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  customize: !include customize.yaml

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

config:
conversation:
discovery:
frontend:
  themes: !include themes.yaml
history:
logbook:
logger:
recorder:
  purge_interval: 1
  purge_keep_days: 30
system_health:
sun:
tts:
  platform: google_translate
updater:

automation: !include automations.yaml
camera: !include cameras.yaml
group: !include groups.yaml
hacs:
  token: e575c4a7328f50587454fad0996fd41c504572ba
lifx:
sensor: !include_dir_merge_list sensor
scene: !include scenes.yaml
script: !include scripts.yaml
smartir:
switch: !include switches.yaml

circadian_lighting:
  min_colortemp: 2500
  max_colortemp: 6000
  sunset_offset: 00:15:00
  transition: 1

google_assistant:
  project_id: homeassistant-163102
  service_account: !include google_service_account.json
  report_state: true
  exposed_domains:
    - climate
    - light
    - media_player
    - scene
    - switch

media_player:
  - platform: plex
  - platform: smartir
    name: Living room TV
    unique_id: living_room_tv
    device_code: 1000
    controller_data: 10.0.73.83

nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret

weather:
  - platform: darksky
    api_key: !secret darksky_api_key

# not worknig
# zoneminder:
#   - host: cameras.zentrification.lan
#     path: "/"
#     path_zms: "/cgi-bin/nph-zms"

