homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 42.35190783223174
  longitude: -71.04626655578613
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 10
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google

group: !include groups.yaml

########################################################################

camera:
  - platform: generic
    name: Commons Balcony
    still_image_url: http://73.219.239.63:84/cgi-bin/camera?resolution=1024
  - platform: mjpeg
    name: Teaparty Boat
    mjpeg_url: http://108.49.186.55/mjpg/video.mjpg
  - platform: generic
    name: I93 Somerville
    still_image_url: https://mass511.com/map/Cctv/406443--1
  - platform: generic
    name: I90 Allston
    still_image_url: https://mass511.com/map/Cctv/407977--1
  - platform: generic
    name: I90 Brighton
    still_image_url: https://mass511.com/map/Cctv/407977--1
  - platform: generic
    name: I93 Dorchester
    still_image_url: https://mass511.com/map/Cctv/1107--1

device_tracker:
  - platform: unifi
    host: 10.0.73.20
    username: chris
    password: !secret unifi_password
    verify_ssl: false

nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret

light:
  - platform: lifx

sensor: !include_dir_merge_list sensor

# Flux
########################################################################
# also can leave switch turned off, and call switch.flux_update

switch:
  - platform: flux
    name: Adjust lights to sun
    lights:
      - light.bedroom
      - light.office
    start_colortemp: 6000
    disable_brightness_adjust: True
    mode: mired

automation:
  - alias: 'HA Start'
    trigger:
      platform: event
      event_type: homeassistant_start
    action:
      service: homeassistant.turn_on
      entity_id: switch.adjust_lights_to_sun

  - alias: 'Automatic Brightness'
    trigger:
      platform: sun
      event: sunset
      offset: '00:10:00'
    action:
      service: light.turn_on
      entity_id: light.office
      data:
        Brightness: 10
