homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 10
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  customize: !include customize.yaml

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

config:
conversation:
discovery:
frontend:
history:
logbook:
sun:
tts:
  platform: google
updater:

automation: !include automation.yaml
camera: !include cameras.yaml
group: !include groups.yaml
lifx:
sensor: !include_dir_merge_list sensor
scene: !include scenes.yaml
switch: !include switches.yaml

device_tracker:
  - platform: unifi
    host: 10.0.73.20
    username: chris
    password: !secret unifi_password
    verify_ssl: false

media_player:
  - platform: plex

nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret

script:
  projector_brightness:
    sequence:
      - service: switch.broadlink_send_packet_10_0_73_83
        data:
          packet:
            - "JgB+AAABE40QFA4UDxYNFA82DzYSMxA1EI4PEw83DzYPERIUDxQNFRA2DwACswABFI0REg8TDxYOEw82EDYPNg83Do8PEw44DzUPFQ8UDhMPFBA2DgACtQABE4wOFhATDxQNFQ83EDUPNw82D4wREw82DzYPFQ8UDhQOFQ82DwANBQAAAAAAAAAAAAA="
            - "JgCAAAABFIwREhATEBIQExA1EDYQNRA1EIwRNRASEBMQExASEBMQExA1EAAC1QABFIwREhASEBMQExA1EDURNRA1EIwRNBATEBMQEhATEBMQEhA2EL8LAAILAAEUjBASEBMQExASEDURNRA1EDYQixE1EBIREhATEBMQEhATEDUQAA0FAAAAAAAAAAA="
            - "JgB+AAABFIwREhASEBMQExA1EDUQNhA1EIwQNhA1EDUQExATEBMPExA1EAACkAABFYwQEhATEBMQEhA2EDUQNRA2EIwQNRA1EDYQEhATEBMQEhA2EAACkAABFIwRERATEBMQExA1EDUQNhA1EIwQNRA2EDUQExASEBMQExA1EAANBQAAAAAAAAAAAAA="
            - "JgCAAAABFIwREhATEBIQExA1EDYQNRA1EIwRNRASEBMQExASEBMQExA1EAAC1QABFIwREhASEBMQExA1EDURNRA1EIwRNBATEBMQEhATEBMQEhA2EL8LAAILAAEUjBASEBMQExASEDURNRA1EDYQixE1EBIREhATEBMQEhATEDUQAA0FAAAAAAAAAAA="
            - "JgB+AAABE40QFA4UDxYNFA82DzYSMxA1EI4PEw83DzYPERIUDxQNFRA2DwACswABFI0REg8TDxYOEw82EDYPNg83Do8PEw44DzUPFQ8UDhMPFBA2DgACtQABE4wOFhATDxQNFQ83EDUPNw82D4wREw82DzYPFQ8UDhQOFQ82DwANBQAAAAAAAAAAAAA="
            - "JgB+AAABE40QFA4UDxYNFA82DzYSMxA1EI4PEw83DzYPERIUDxQNFRA2DwACswABFI0REg8TDxYOEw82EDYPNg83Do8PEw44DzUPFQ8UDhMPFBA2DgACtQABE4wOFhATDxQNFQ83EDUPNw82D4wREw82DzYPFQ8UDhQOFQ82DwANBQAAAAAAAAAAAAA="
  # tv_time:
  #   sequence:
  #     - service: switch.broadlink_send_packet_10_0_73_83
  #       data:
  #         packet:
  #           - 'JgAgAQABJZQRFBA5ERQROBEUETgRORA5ETgROBE4ERQRFBEUETkQORE4ETgRORAVEDkRFBEUERQQFRAVEBUQOREUETgROBE5EAAE2QABJZQRFBA5ERQROBEUETgROBE5ETgROBE4ERQRFBEUETkQORE4ETgRORAVEDkRFBEUETgRFBEUERQROBEUETgRORAVEAAE2QABJZQSExE4ERQROBEUETgRORA5ETgROBE5EBUQFRAVEDkROBE4ETgRORAVEDkRFBEUETgRFBEUERQROBEUETgRORAVEAAE2QABJZQRFBA5ERQQOREUETgROBE5EDkROBE4ERQRFBEUETgRORA5ETgROBEUETkQFRAUETkRFBAVEBUQOREUETgROBEUEQANBQAAAAAAAAAA'
  #           - 'JgBQAAABIZMRNxE4ERMRExEUEBQRExE4EDgRExEUEBQRNxEUEBQRExE4ETcROBAUERMRExEUEBQRExETERQQOBE4EDgROBA4EQAFEAABIkoQAA0FAAAAAAAAAAA='
