dashboard:
  view: yes
  entities:
    - group.automation
    - group.scene
    - group.audio
    - group.projector
    - group.lights
    - group.transit
    - group.climate
    - camera.foscam_camera
    - sun.sun
    - device_tracker.amazonc5ea57c50
    - device_tracker.camus
    - device_tracker.clamence
    - device_tracker.galaxys7
    - device_tracker.ibaby_608nacuv
    - device_tracker.tap613302h7
    - device_tracker.xboxone
    - updater.updater

media:
  view: yes
  entities:
    #- camera.miami
    - media_player.65_tcl_roku_tv_3
    - media_player.chrome_1
    - media_player.chrome_2

weather:
  view: yes
  entities:
    - group.nest
    - group.darksky

# Groups
############################################################
audio:
  name: Audio
  entities:
    #- scene.projector_time
    # - light.lifx_d073d5109e46
    # - sensor.bedroom_thermostat_humidity
    # - climate.bedroom
    #- switch.cablebox
    - switch.tv
    - switch.rotel
    - switch.rotel_volume
    - switch.rotel_input_1
    - switch.rotel_input_2

automation:
  name: Automation
  entities:
    - automation.automatic_brightness
    - automation.ha_start

climate:
  name: Climate
  entities:
    - climate.hallway
    - sensor.hallway_thermostat_humidity
    - sensor.dark_sky_humidity
    - sensor.dark_sky_temperature
    - sensor.dark_sky_minutely_summary

darksky:
  name: Dark Sky
  entities:
    - sensor.dark_sky_temperature
    - sensor.dark_sky_apparent_temperature
    - sensor.dark_sky_humidity
    - sensor.dark_sky_ozone
    - sensor.dark_sky_wind_speed
    - sensor.dark_sky_minutely_summary

lights:
  name: Lights
  entities:
    - light.lifx_d073d5389945
    - light.lifx_d073d538b38a
    - light.lifx_d073d538943a
    - light.office
    - light.lifx_d073d5109e46
    - light.office2
    - light.l2
    - light.kitchen
    - switch.fluxer

nest:
  name: Nest
  entities:
    - binary_sensor.hallway_thermostat_fan
    - sensor.hallway_thermostat_hvac_state
    - climate.hallway
    - sensor.hallway_thermostat_humidity
    - sensor.hallway_thermostat_temperature
    - sensor.hallway_thermostat_target
    - sensor.hallway_thermostat_operation_mode
    - binary_sensor.hallway_thermostat_online

projector:
  name: Projector
  entities:
    - switch.projector
    - script.projector_brightness

scene:
  name: Scene
  entities:
    - scene.movie_time

transit:
  name: Transit
  entities:
    - sensor.lyft_time
    #- sensor.transit_brickell
    #- sensor.transit_miami_beach
