# https://github.com/probonopd/irdb
# https://github.com/molexx/irdb2broadlinkha
# https://gist.githubusercontent.com/appden/42d5272bf128125b019c45bc2ed3311f/raw/bdede927b231933df0c1d6d47dcd140d466d9484/pronto2broadlink.py
# https://github.com/mjg59/python-broadlink/issues/90
# https://community.home-assistant.io/t/configuration-of-broadlink-ir-device-and-getting-the-right-ir-codes/48391


- platform: broadlink
  host: 10.0.73.83
  mac: '34:ea:34:42:ac:d2'
  timeout: 15
  switches:
    projector:
      command_on: 'JgB+AAABFIwREhATDxMQExA1EDYQNRA2EIwSEBATEBMQExASEBMQNRATEAAC+AABFYwREhASEBMQExA1EDUQNhA1EIwQExATEBIQExATEBIQNhATEAAC+AABFIwREhATEBIQExA2EDUQNRA2EIwQExASEBMQExASEBMQNRATEAANBQAAAAAAAAAAAAA='
      command_off: 'JgB+AAABFIwREhATDxMQExA1EDYQNRA2EIwSEBATEBMQExASEBMQNRATEAAC+AABFYwREhASEBMQExA1EDUQNhA1EIwQExATEBIQExATEBIQNhATEAAC+AABFIwREhATEBIQExA2EDUQNRA2EIwQExASEBMQExASEBMQNRATEAANBQAAAAAAAAAAAAA='
    rotel:
      command_on: 'JgBQAAABJpQRORA5ERMSEhEUEBQRExE4ETkQFBETERQQOBEUEBQRExETERQRExAUERMRExAWDxQQORE4EjgQORE4ETgSOBA5EQAFjQABJUwRAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABJpQRORA5ERMSEhEUEBQRExE4ETkQFBETERQQOBEUEBQRExETERQRExAUERMRExAWDxQQORE4EjgQORE4ETgSOBA5EQAFjQABJUwRAA0FAAAAAAAAAAA='
    rotel_volume:
      command_on: 'JgBQAAABJZYOOw84ERQQFRAUEBUOFRE4EToOFQ8WDxUPOg8VEBUOFw0WEDcSOQ8WDjoRFA8UEBUPOxMRDxUQORAVDjsPOBM3EAAFjgABJE0PAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABJpQSNxI4DxYPFRATERQRExE4EDkRExEUERIROg8VEBQRExA4EzcROBEUEDkQFBAVEBQQFBAUEBQQORAVETgQOBE5EAAFjQABJE0RAA0FAAAAAAAAAAA='
    rotel_inputs:
      command_on: 'JgBQAAABIpIRNxE4ERMSEhETERQQFBE3ETgRExETERQQOBETERMRFBAUERMRExE4ERMRExETExIQOBE4EDgRExE4EDgROBA4EQAFDwABIUoRAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABIZMRNxE4ERMRExEUEBQRExE4EDgRExEUEBQRNxEUEBQRExE4ETcROBAUERMRExEUEBQRExETERQQOBE4EDgROBA4EQAFEAABIkoQAA0FAAAAAAAAAAA='
    rotel_input_1:
      command_on: 'JgBQAAABIZMRNxE4ERMRExEUEBQRExE4EDgRExEUEBQRNxEUEBQRExE4ETcROBAUERMRExEUEBQRExETERQQOBE4EDgROBA4EQAFEAABIkoQAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABIZMRNxE4ERMRExEUEBQRExE4EDgRExEUEBQRNxEUEBQRExE4ETcROBAUERMRExEUEBQRExETERQQOBE4EDgROBA4EQAFEAABIkoQAA0FAAAAAAAAAAA='
    rotel_input_2:
      command_on: 'JgBQAAABIpIRNxE4ERMSEhETERQQFBE3ETgRExETERQQOBETERMRFBAUERMRExE4ERMRExETExIQOBE4EDgRExE4EDgROBA4EQAFDwABIUoRAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABIpIRNxE4ERMSEhETERQQFBE3ETgRExETERQQOBETERMRFBAUERMRExE4ERMRExETExIQOBE4EDgRExE4EDgROBA4EQAFDwABIUoRAA0FAAAAAAAAAAA='

# http://www.ipcamcontrol.net/files/Foscam%20IPCamera%20CGI%20User%20Guide-V1.0.4.pdf
- platform: command_line
  switches:
    foscam_security:
      command_on: "~/bin/foscam.sh security_on"
      command_off: "~/bin/foscam.sh security_off"
      command_state: "~/bin/foscam.sh motion"
      value_template: '{{ value == "1" }}'
    foscam_pan:
      command_on: "~/bin/foscam.sh left"
      command_off: "~/bin/foscam.sh right"
    foscam_tilt:
      command_on: "~/bin/foscam.sh up"
      command_off: "~/bin/foscam.sh down"
    foscam_zoom:
      command_on: "~/bin/foscam.sh in"
      command_off: "~/bin/foscam.sh out"
    foscam_reset:
      command_on: "~/bin/foscam.sh reset"
      command_off: "~/bin/foscam.sh reset"
    tv:
      command_on: 'curl -X POST http://10.0.73.50:8060/keypress/PowerOn'
      command_off: 'curl -X POST http://10.0.73.50:8060/keypress/PowerOff'
      command_state: 'curl -s GET http://10.0.73.50:8060/query/device-info | grep power-mode | sed -e "s:.*<power-mode>\(.*\)</power-mode>.*:\1:"'
      value_template: '{{ value == "PowerOn" }}'

# - platform: flux
#   name: fluxer
#   lights:
#     - light.counter1
#     - light.counter2
#     - light.office
#     - light.kitchen1
#     - light.kitchen2
#     - light.kitchen3
#     - light.living1
#     - light.living2
#   start_colortemp: 6000
#   sunset_colortemp: 3000
#   stop_colortemp: 2500
#   disable_brightness_adjust: True
#   mode: mired
#   transition: 1
#   interval: 90

- platform: circadian_lighting
  min_brightness: 30
  lights_ct:
    - light.bedroom1
    - light.counter1
    - light.counter2
    - light.office1
    - light.kitchen1
    - light.kitchen2
    - light.kitchen3
    - light.living1
    - light.living2
    - light.living3
