- platform: command_line
  name: Bus to Work Arrives
  command: ~/bin/cornelia_next_bus.sh

- platform: google_travel_time
  api_key: !secret google_api_key
  name: Time to Trader Joes
  friendly_name: Time to trader joes
  origin: 85 seaport blvd, Boston, MA
  destination: 748 Memorial Drive, Cambridge, MA
  #options:
  #  mode: transit

