- platform: darksky
  api_key: !secret darksky_api_key
  forecast:
    - 0
  hourly_forecast:
    - 0
    - 1
  monitored_conditions:
    - summary
    - icon
    - precip_type
    - precip_intensity
    - precip_probability
    - precip_accumulation
    - temperature
    - apparent_temperature
    - dew_point
    - wind_speed
    - wind_gust
    - wind_bearing
    - cloud_cover
    - humidity
    - pressure
    - visibility
    - ozone
    - minutely_summary
    - hourly_summary
    - daily_summary
    - uv_index
    - nearest_storm_distance
    - nearest_storm_bearing

- platform: moon

# zone found here
# https://www.weather.gov/pimar/PubZone
- platform: weatheralerts
  state: FL
  zone: "074"
